on:
  workflow_dispatch:

jobs:
  upload-release-to-test-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for Trusted Publishing
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Release Assets
        env:
          GH_TOKEN: ${{ github.token }} # Is this secure?
        run: |
          mkdir dist
            gh release download 10.0.1 --dir dist --pattern "*"
      #          gh release download ${{ github.event.release.tag_name }} --dir dist --pattern "*"
      - name: List files to verify
        run: ls -R dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
